import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import StyledComponentsRegistry from '../lib/registry'
import GlobalStyles from '@/styles/GlobalStyles'
import Header from '@/components/Header'
import ProductsProvider from '@/contexts/products'
import LoginProvider from '@/contexts/login'

const inter = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductsProvider>
          <LoginProvider>
            <StyledComponentsRegistry>
              <GlobalStyles />
              <Header />
              {children}
            </StyledComponentsRegistry>
          </LoginProvider>
        </ProductsProvider>
      </body>
    </html>
  )
}
